### ISSUE TITLE
how to eval

### ISSUE THREAD

**Issue by tifeng** [manirupa/phrase2vecGLM#1]
I have a question that I can't find the file "./runeval.py" in step 9.And could you tell me how to get the qrel file of this track? Thanks a lot!

**Comment by manirupa** [comment]
Hello -- thank you for the question and pointing it out. The **_TRECscripts_materials_** folder has now been added, which contains the runevals.py script, as well as the qrels file, where **_qrels-sampleval-2016.txt_** is the correct one to be considered for this work (already used by runevals.py)
